name: ✨ Feature Request
description: 建議新功能 / Suggest a feature
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: 想解決咩問題？ Problem statement
      description: 講下背景同痛點（建議方案都可以一齊寫喺度）
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建議方案 Proposed solution
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: 其他方案 Alternatives considered
    validations:
      required: false
